export const termekek = [
	{
		id: 0,
		name: "cipo1",
		url: "1.jpg",
		leiras: "Ez egy cipő. A neve: cipo1",
		price: 1000,
		mennyiseg: 1,
	},
	{
		id: 1,
		name: "cipo2",
		url: "2.jpg",
		leiras: "Ez egy cipő. A neve: cipo2",
		price: 1500,
		mennyiseg: 1,
	},
	{
		id: 2,
		name: "cipo3",
		url: "3.jpg",
		leiras: "Ez egy cipő. A neve: cipo3",
		price: 2000,
		mennyiseg: 1,
	},
	{
		id: 3,
		name: "cipo4",
		url: "4.jpg",
		leiras: "Ez egy cipő. A neve: cipo4",
		price: 2500,
		mennyiseg: 1,
	},
	{
		id: 4,
		name: "cipo5",
		url: "5.jpg",
		leiras: "Ez egy cipő. A neve: cipo5",
		price: 3000,
		mennyiseg: 1,
	},
	{
		id: 5,
		name: "cipo6",
		url: "6.jpg",
		leiras: "Ez egy cipő. A neve: cipo6",
		price: 3500,
		mennyiseg: 1,
	},
]
